#define NUM_CMDS 39

String payloads[NUM_CMDS] = { "Power On",
                              "Power Off",
                              "Keystone",
                              "Mute",
                              "Freeze",
                              "Menu",
                              "Up",
                              "Down",
                              "Right",
                              "Left",
                              "Re-Sync",
                              "Source Analog RGB for D-sub",
                              "Source PbPr for D-sub",
                              "Source S-Video",
                              "Source Composite Video",
                              "Source Component Video",
                              "Aspect ratio 16:9",
                              "Aspect ratio 4:3",
                              "Volume +",
                              "Volume -",
                              "Brightness",
                              "Contrast",
                              "Color Temperature",
                              "Hide",
                              "Source",
                              "Video: Color saturation adjustment",
                              "Video: Hue adjustment",
                              "Video: Sharpness adjustment",
                              "Query Model name",
                              "Query Native display resolution",
                              "Query company name",
                              "Aspect ratioL.Box",
                              "Keystone Up",
                              "Keystone Down",
                              "Zoom",
                              "e-Key",
                              "Color RGB",
                              "Language",
                              "Source HDMI" };

String codes[NUM_CMDS] = { "* 0 IR 001\r",
                           "* 0 IR 002\r",
                           "* 0 IR 004\r",
                           "* 0 IR 006\r",
                           "* 0 IR 007\r",
                           "* 0 IR 008\r",
                           "* 0 IR 009\r",
                           "* 0 IR 010\r",
                           "* 0 IR 011\r",
                           "* 0 IR 012\r",
                           "* 0 IR 014\r",
                           "* 0 IR 015\r",
                           "* 0 IR 017\r",
                           "* 0 IR 018\r",
                           "* 0 IR 019\r",
                           "* 0 IR 020\r",
                           "* 0 IR 021\r",
                           "* 0 IR 022\r",
                           "* 0 IR 023\r",
                           "* 0 IR 024\r",
                           "* 0 IR 025\r",
                           "* 0 IR 026\r",
                           "* 0 IR 027\r",
                           "* 0 IR 030\r",
                           "* 0 IR 031\r",
                           "* 0 IR 032\r",
                           "* 0 IR 033\r",
                           "* 0 IR 034\r",
                           "* 0 IR 035\r",
                           "* 0 IR 036\r",
                           "* 0 IR 037\r",
                           "* 0 IR 040\r",
                           "* 0 IR 042\r",
                           "* 0 IR 043\r",
                           "* 0 IR 046\r",
                           "* 0 IR 047\r",
                           "* 0 IR 048\r",
                           "* 0 IR 049\r",
                           "* 0 IR 050\r" };
